// Code generated by foggo; DO NOT EDIT.

package poolerchan

import (
	"context"
	"log"
)

type PoolOption interface {
	apply(*Pool)
}

type numberOfJobsOption struct {
	numberOfJobs int
}

func (o numberOfJobsOption) apply(s *Pool) {
	s.numberOfJobs = o.numberOfJobs
}

type numberOfWorkersOption struct {
	numberOfWorkers int
}

func (o numberOfWorkersOption) apply(s *Pool) {
	s.numberOfWorkers = o.numberOfWorkers
}

type loggerOption struct {
	logger *log.Logger
}

func (o loggerOption) apply(s *Pool) {
	s.logger = o.logger
}

type ctxOption struct {
	ctx context.Context
}

func (o ctxOption) apply(s *Pool) {
	s.ctx = o.ctx
}
